name: "Pull Request Reviewer"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    if: ${{ github.actor != 'modular-magician' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: uesteibar/reviewer-lottery@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
